"""Metrics Rollup model — Hourly aggregates for admin dashboard charts.

Purpose: pre-computed hourly buckets for fast cost/failure/approval
charts without scanning raw audit_events. Generated by a periodic job.
"""

from datetime import datetime

from sqlalchemy import BigInteger, Integer, Numeric, String, DateTime
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy import func

from app.models.base import Base


class MetricsRollupHourly(Base):
    """Hourly aggregated metrics per department/agent.

    Composite PK: (bucket_start, department, agent_id, metric_scope).
    Generated by the rollup job (Celery beat or cron).
    """

    __tablename__ = "metrics_rollups_hourly"

    bucket_start: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), primary_key=True,
        comment="Start of the hourly bucket, e.g. 2026-02-12 10:00:00+00",
    )
    department: Mapped[str] = mapped_column(
        String(50), primary_key=True, index=True,
    )
    agent_id: Mapped[str] = mapped_column(
        String(255), primary_key=True, server_default="*",
        comment="Agent ID or '*' for department-level aggregation",
    )
    metric_scope: Mapped[str] = mapped_column(
        String(20), primary_key=True, server_default="dept",
        comment='"dept"|"agent"',
    )

    # ── Trace counts ─────────────────────────────
    traces_started: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    traces_completed: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    traces_failed: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    traces_needs_approval: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")

    # ── Tool stats ───────────────────────────────
    tool_calls: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    tool_denied: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    tool_failed: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")

    # ── LLM stats ────────────────────────────────
    llm_calls: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    llm_failed: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    tokens_in: Mapped[int] = mapped_column(BigInteger, nullable=False, server_default="0")
    tokens_out: Mapped[int] = mapped_column(BigInteger, nullable=False, server_default="0")
    cost_usd: Mapped[float] = mapped_column(Numeric(14, 6), nullable=False, server_default="0")

    # ── Approval stats ───────────────────────────
    approval_requests: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    approvals_granted: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    approvals_denied: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    approval_latency_ms_p50: Mapped[int | None] = mapped_column(Integer, nullable=True)
    approval_latency_ms_p95: Mapped[int | None] = mapped_column(Integer, nullable=True)

    # ── Execution stats ──────────────────────────
    execution_time_ms_p50: Mapped[int | None] = mapped_column(Integer, nullable=True)
    execution_time_ms_p95: Mapped[int | None] = mapped_column(Integer, nullable=True)

    def __repr__(self) -> str:
        return f"<MetricsRollup {self.bucket_start} {self.department}/{self.agent_id}>"
